### ISSUE TITLE
alert message box does not work with 2 commands

### ISSUE THREAD

**Issue by hablaporinternet** [CryptoMF/frostybot-js#3]
I need two commands from tradingview alert: The first line will cancel any existing open orders on BTC-PERP, and the second command will create a market order. One command per text line. Please see the attached screenshots.

Frosty debug console shows the error message:
"Unknown Module: this".

When we use one line in the tradingview alert box, the command is successfully completed. One command only.  

Please advise how to send more than 1 command; like cancellall and long/short in the same alert.

![Frostyissue1](https://user-images.githubusercontent.com/27828597/99480737-afcee500-2926-11eb-832b-c475021ec76a.png)
![Frostyissue2](https://user-images.githubusercontent.com/27828597/99480745-b5c4c600-2926-11eb-8dfc-dc602c711f82.png)

**Comment by CryptoMF** [comment]
Issue has been corrected

[https://github.com/CryptoMF/frostybot-js/commit/d22954dd70decbe28dc7d5cd3dbda3df90c54ee9](https://github.com/CryptoMF/frostybot-js/commit/d22954dd70decbe28dc7d5cd3dbda3df90c54ee9)
