### ISSUE TITLE
Blank password

### ISSUE THREAD

**Issue by hspeight** [CryptoMF/frostybot-js#39]
Whilst changing my password I accidentally pressed enter with the new password blank and it was accepted.
I then logged out and was able to log back in without a password.

**Comment by CryptoMF** [comment]
Fix in commit [e01144fbc6863d3ab30c3e23d99d9abd36a4d188](https://github.com/CryptoMF/frostybot-js/commit/e01144fbc6863d3ab30c3e23d99d9abd36a4d188)
