### ISSUE TITLE
Account calculation don't show correct on gui

### ISSUE THREAD

**Issue by riodda** [CryptoMF/frostybot-js#43]
I have connected my binance account on a new stub, i've retrived the account balance but there is a discrepancy between the account on the gui, on binance and on the console.
If I retrive from the console I have all the correct positions same as on binance account, but from gui each position is trated as trade with several other currencies (some also FIAT) some of them i have never traded.

![image](https://user-images.githubusercontent.com/13453063/109688617-c66f1400-7b84-11eb-9d30-43c90c43da17.png)

**Comment by CryptoMF** [comment]
This is a result of spot positions getting paired with all available pairs so that the underlying trading logic can work.

I do understand that its misleading, so I will remove spot positions from the "Positions" view, and add a "Balances" view where spot balances can be seen.

**Comment by CryptoMF** [comment]
This can now be disabled in the GUI, closing this issue
