### ISSUE TITLE
Options sometimes not saving on the GUI

### ISSUE THREAD

**Issue by driesvandenbroecke** [CryptoMF/frostybot-js#54]
Sometimes the options i select don't save. Green box doesn't appear after filling in the box, sometimes a reload of the page isn't enough. Maybe add a save button on the bottom of the page in case you want to be sure it's saved?

**Comment by CryptoMF** [comment]
Hi, thi could be an issue with your session. Are you login into Frostybot from multiple sources? Please could you let me know what the log says when the options fail to save.

**Comment by CryptoMF** [comment]
Is this resolved? Can I close the issue?
