### ISSUE TITLE
Error code -2020 Unable to fill

### ISSUE THREAD

**Issue by shaunlab** [CryptoMF/frostybot-js#68]
Hi,

I just set up frostybot locally and am doing some test runs on the Testnet Binance Futures API. Starting off with trying to do a simple buy order although am getting:

![image](https://user-images.githubusercontent.com/41994429/118272292-b481e980-b4c2-11eb-8d45-8fca48daba33.png)

**Comment by CryptoMF** [comment]
The Biance Futures testnet has zero liquidity and is basically useless. I'll get a lot of errors on there for sure.

**Comment by shaunlab** [comment]
Thank you!
