### ISSUE TITLE
amount: infinity

### ISSUE THREAD

**Issue by shaunlab** [CryptoMF/frostybot-js#69]
Hi,
I've just set up Frostybot locally and am trying to place a simple test buy order: frostybot trade:shaun_test:buy symbol=DOGE/USDT size=100 which results in:

![image](https://user-images.githubusercontent.com/41994429/118272798-6f11ec00-b4c3-11eb-8516-7c0ae9263934.png)

I'm not too sure what the amount: infinity is and why the order is failing? If I switch the "size" parameter in the command and use base instead it resolves the amount: infinity issue although the testnet exchange then returns error: "-2020 UNABLE_TO_FILL"
Also not sure about the "Order submission failed: Error: Infinity: invalid number (contains an illegal character 'I')" I'm seeing in the log.
Also it takes roughly 100 seconds for the logging results to return, just wondering why it takes so long?

**Comment by CryptoMF** [comment]
Yeah, as with the previous issue you logged, the problem here is the Binance Futures testnet liquidity. Rest assured this works of the live net

**Comment by shaunlab** [comment]
Thanks!
