### ISSUE TITLE
Trade execution time

### ISSUE THREAD

**Issue by shaunlab** [CryptoMF/frostybot-js#70]
Hi,
I just switched from Binance Futures TestNet to Binance live to run a quick test. 
The turn around time from placing the order to the order being placed took 25 seconds.
It feels rather slow - any reason or factors I should consider as to the slow turn around time?

![image](https://user-images.githubusercontent.com/41994429/118276436-f1041400-b4c7-11eb-9904-6a3bf99484fe.png)

**Comment by CryptoMF** [comment]
Yeah, the stable version is a bit slow, but we have a brand new websocket version in the development branch that can place orders in less than 1 second

**Comment by shaunlab** [comment]
Thanks, will def check it out!
