### ISSUE TITLE
Profit & Loss function

### ISSUE THREAD

**Issue by shimuldn** [CryptoMF/frostybot-js#73]
I have just started using Frostybot with tradingview webhook.
I am new to the trading and tradingview. Tried to use 3commas. There settings are too complicated or restricted. I am even not able to find out a way to manage the safety/topup order from the tradingview strategies. After wasting many hours and testing different bots found the Frosy.

The tradingview strategie started making order and 1st safety order was successful and started loving the frosty already. Didn't make any profit yet but I am hopeful with the current strategie.

**_Hope the feture working soon at list with the basic function. It's really hard to calculate the profit without this._**

Not sure about this idea but if there is some good tested tradingview strategies with recommendation on wiki would be great for begainer like me.

Sorry for my long story. 

Thank you for creating this FrostyBot

**Comment by CryptoMF** [comment]
Hi there

Thank you very much for your kind words and I'm happy that you are finding Frostybot useful. 

To answer your comment regarding the strategies, I've purposefully tried not to do that, as I'd like people to be able to use their own strategies and instead focus my efforts on the Frostybot platform. The codebase is huge and complex and I don't really have the spare time to invest in Pine code devleopment as well.

However, In the #tradingview-strategies channel on our Discord, I have posted a strategy there called Redflow, which showcases how Tradingview strategies can be dynamically incorporated into Frostybot, and I've dedicated a page on the Wiki to explaining the integration as well. A lot of other people have posted some really cool Tradingview stuff in the Discord which you may find quite useful as well.

Anyway, I am happy that you are enjoying Frostybot! Let me know if there is any help you need to get up and running.
