### ISSUE TITLE
This does not work at all 

### ISSUE THREAD

**Issue by mrdamfur** [CryptoMF/frostybot-js#74]
this does not work at all i have tried you instructions 3 time even did the Amazon one and paid for it.. I am tired of software that claims to work but doen't

**Comment by CryptoMF** [comment]
I'm sorry you feel that way.

We have a big Discord community of people willing to assist you if need
assistance.

Saying something "does not work at all" without posting any logs or
screenshots for us to assist you really doesn't help much at all.
