### ISSUE TITLE
Stoploss - Index price

### ISSUE THREAD

**Issue by Drtitel** [CryptoMF/frostybot-js#77]
Hello,

First of all I would like to thank Frostybot, it's a great service.

I use stoploss order but there is no option to choose between index, mark and last price which are available on Bitmex. Is there any possibility to enter stoploss with Index price? If not, is this option planned in the future?

Thank you for your reply

**Comment by CryptoMF** [comment]
Good day

You can use the triggertype parameter for this purpose

triggertype=last/mark/index

**Comment by Drtitel** [comment]
Thank you, works!!
