### ISSUE TITLE
Frostybot crash after few days

### ISSUE THREAD

**Issue by Drtitel** [CryptoMF/frostybot-js#82]
Hi Andrew,

frostybot crashes after few days. There is no error or something what could be causing the error. It's the same every time. I start frostybot, it runs for a few days and executes commands, but after a few days frostybot crashes and I have to turn it back on. I thought the problem might be in and Ubuntu updates, so I disabled them, however that didn't help and yesterday frostybot crashed again. I am using the following server configuration:

Ubuntu 18.04.5
RAM 512MB used 33%
5GB HDD
1x vCPU

Thank you for advice!
Patrik

**Comment by CryptoMF** [comment]
Hi

Some other users have reported similar issues, however I've not experienced
it myself on a 4-core server with 4GB RAM.

An autorestart script is pinned in the Discord which will
automatically restart your Frostybot if it crashes.

**Comment by Drtitel** [comment]
Hi,

well, thank you for advice. I try used script for autorestart and also used PM2 command for this script to stay running. It seems to work. Forstybot now works smoothly for a week. 

Thank you
Patrik
