### ISSUE TITLE
Multiple strategies

### ISSUE THREAD

**Issue by dorienh** [CryptoMF/frostybot-js#84]
Say I have 3 trading bots: 

- one for ETHUSD
- one for ETHUSD (different strategy)
- one for LTCUD

I want to distribute my capital evenly across the bots. I can give the orders a 33% of capital amount, but what if one of the other strategies already has an open position, the 33% of 66% (remaining USD) would not be correct. 

How do people deal with this? Do you use subaccounts on Binance or FTX? Seems complex.

**Comment by CryptoMF** [comment]
Probably I'd use FTX subaccounts for that, but yeah, seems like a pain in
the ass

**Comment by dorienh** [comment]
Yeah I'll have to make do! :) If ever a feature appears that can keep track of separate soft 'accounts' within an exchange account, would be great.
