### ISSUE TITLE
Advise on subscriptions / selling your frostybot

### ISSUE THREAD

**Issue by dorienh** [CryptoMF/frostybot-js#85]
This may be beyond the scope of this repo, but would appreciate any advise. Say at some point one was to commercialize their strategies. Any recommendations on how to securely hook a subscription site onto Frosty?

**Comment by CryptoMF** [comment]
Hi Dorien

Frostybot already has some built-in capability for signal
providers/resellers. DM me on Discord and I'll talk you through it.

Cheeers

**Comment by dorienh** [comment]
Thanks, will do!
